version: '3.7'
services:

  postgres-keycloak:
    container_name: postgres-keycloak
    image: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - ./postgres-keycloak:/data/postgres
    expose:
      - "5434"
    ports:
      - "5434:5434"
    command: -p 5434
    restart: always

  postgres-main:
    image: postgres
    container_name: postgres-main
    environment:
      POSTGRES_DB: main-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - ./postgres-main:/data/postgres
    expose:
      - "5433"
    ports:
      - "5433:5433"
    command:
      - postgres
      - -c
      - max_connections=200
      - -p
      - "5433"
    restart: always

  ## Keycloak Docker Compose Config
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:23.0.3
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres-keycloak:5434/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
      - KC_FEATURES=token-exchange,admin-fine-grained-authz
      - KC_LOG_LEVEL=ALL
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
    command:
      - start-dev
    volumes:
      - ./auth/import:/opt/keycloak/data/import
    expose:
      - "8443"
    ports:
      - "8443:8080"
    depends_on:
      - postgres-keycloak


  ## Main-Service Docker Compose Config
  erasmus-service:
    container_name: erasmus-service
    image: smeloved/erasmus-service:latest
    ports:
      - "8100:8100"
    environment:
      - SPRING_PROFILES_ACTIVE=local
